name: fun_with_flags
description: Add and retrieve a data asset.

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  data_assets: any
  hooks: any
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
