name: assets
description: Placeholder for a Dart asset bundle system.
version: 0.0.2
repository: https://github.com/mosuem/assets

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
