# Copyright (c) 2022, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

name: jnigen
description: A Dart bindings generator for Java and Kotlin that uses JNI under the hood to interop with Java virtual machine.
version: 0.8.1-wip
repository: https://github.com/dart-lang/native/tree/main/pkgs/jnigen

environment:
  sdk: '>=3.3.0 <4.0.0'

topics:
  - interop
  - ffi
  - codegen
  - java
  - jni

dependencies:
  json_annotation: ^4.8.0
  package_config: ^2.1.0
  path: ^1.8.0
  pub_semver: ^2.1.4
  args: ^2.3.0
  yaml: ^3.1.0
  logging: ^1.0.2
  meta: ^1.8.0
  cli_config: '>=0.1.0 <0.3.0'

dev_dependencies:
  lints: ^3.0.0
  jni:
    path: ../jni
  test: ^1.24.1
  build_runner: ^2.2.0
  json_serializable: ^6.6.0
