name: link_inverse_package
description: Part of two packages with native assets that try to pass assets upstream.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  hooks: any

dev_dependencies:
  lints: ^6.0.0
