name: wrong_namespace_asset
description: Package that tries to add an asset with an id not prefixed by its package name.
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cli_config: ^0.1.1
  # native_assets_cli: ^0.4.1
  native_assets_cli:
    path: ../../../native_assets_cli/
  yaml: ^3.1.1
  yaml_edit: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
