name: native_toolchain_c
description: >-
  A library to invoke the native C compiler installed on the host machine.
version: 0.16.1-wip
repository: https://github.com/dart-lang/native/tree/main/pkgs/native_toolchain_c

topics:
  - compiler
  - ffi
  - interop
  - native-assets
  - native-toolchain

resolution: workspace

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  code_assets: ^0.19.0
  glob: ^2.1.1
  hooks: ^0.19.0
  logging: ^1.3.0
  meta: ^1.16.0
  pub_semver: ^2.2.0

dev_dependencies:
  collection: ^1.19.1
  custom_lint: ^0.7.5
  dart_flutter_team_lints: ^3.5.1
  repo_lint_rules:
    path: ../repo_lint_rules/
  test: ^1.25.15
