name: simple_link
description: Build 4 assets for linking, only keep two in link.dart.
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cli_config: ^0.2.0
  logging: ^1.1.1
  native_assets_cli:
    path: ../../../native_assets_cli/

dev_dependencies:
  lints: ^3.0.0
  test: ^1.23.1
  path: ^1.9.0
