name: relative_path
description: Outputs a data asset with a relative path.
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  logging: ^1.1.1
  # native_assets_cli: ^0.11.0
  native_assets_cli:
    path: ../../../native_assets_cli/

dev_dependencies:
  lints: ^3.0.0
