name: drop_data_asset
description: Add four data assets, remove three in linking based on recorded usage.

publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  hooks: any
  data_assets: any
  logging: any
  meta: any
  record_use: any

dev_dependencies:
  lints: any
  test: any
