name: complex_link
description: Prints "Tada!", but packages some assets while tree-shaking others
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  cli_config: ^0.2.0
  complex_link_helper:
    path: ../complex_link_helper/
  data_assets: ^0.19.0
  hooks: ^0.19.1
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
  path: ^1.9.0
  test: ^1.25.15
