name: repo_lint_rules
description: Custom lints for this repository
version: 0.1.0-wip

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  analyzer: ^7.3.0
  custom_lint_builder: ^0.7.5
  lints: ^6.0.0
  path: ^1.9.1

dev_dependencies: 
  custom_lint: ^0.7.5
