name: simple_data_asset
description: Add and retrieve a data asset.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.1.1
  native_assets_cli: ^0.10.0
  # native_assets_cli:
  #   path: ../../../native_assets_cli/

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
