name: flag_enthusiast_2
description: A package with a high-level API to load multiple flags.

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  data_assets: any
  fun_with_flags:
    path: ../fun_with_flags
  hooks: any
  logging: ^1.3.0
  meta: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
