name: fail_build
description: Always fails to build
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # native_assets_cli: ^0.11.0
  native_assets_cli:
    path: ../../../native_assets_cli/

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^3.0.0
  test: ^1.23.1
