name: package_with_metadata
description: Sets some metadata in its hook/build.dart
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  native_assets_cli: ^0.5.0
  #  native_assets_cli:
  #    path: ../../../native_assets_cli/
  yaml: ^3.1.1
  yaml_edit: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
