name: transformer
description: Transforms assets, caches the transformation, and caches across build invocations.
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  crypto: ^3.0.6
  # native_assets_cli: ^0.11.0
  native_assets_cli:
    path: ../../../native_assets_cli/

dev_dependencies:
  lints: ^3.0.0
