name: native_assets_builder
description: >-
  This package is the backend that invokes top-level `build.dart` scripts.
version: 0.1.0
repository: https://github.com/dart-lang/native/tree/main/pkgs/native_assets_builder

topics:
  - ffi
  - interop
  - native

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  graphs: ^2.3.1
  logging: ^1.2.0
  native_assets_cli: ^0.1.0
  package_config: ^2.1.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  test: ^1.24.3
  yaml: ^3.1.2
