name: native_assets_builder
description: >-
  This package is the backend that invokes build hooks.
version: 0.8.4-wip
repository: https://github.com/dart-lang/native/tree/main/pkgs/native_assets_builder

publish_to: none

environment:
  # Allow any pre-release version of 3.5.0 and onwards
  # (i.e. 3.5.0-edge*, 3.5.0-dev*, 3.5.0-beta*, ...)
  sdk: '>=3.5.0-0 <4.0.0'

dependencies:
  collection: ^1.18.0
  graphs: ^2.3.1
  logging: ^1.2.0
  # native_assets_cli: ^0.8.0
  native_assets_cli:
    path: ../native_assets_cli/
  package_config: ^2.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
  file_testing: ^3.0.0
  test: ^1.24.3
