name: native_assets_builder
description: >-
  This package is the backend that invokes `build.dart` hooks.
version: 0.6.1
repository: https://github.com/dart-lang/native/tree/main/pkgs/native_assets_builder

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  graphs: ^2.3.1
  logging: ^1.2.0
  native_assets_cli: ^0.5.0
  # native_assets_cli:
  #   path: ../native_assets_cli/
  package_config: ^2.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
  file_testing: ^3.0.0
  test: ^1.24.3
