name: cyclic_link_package_1
description: Part of two packages with native assets that have a cycle.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  cyclic_link_package_2:
    path: ../cyclic_link_package_2
  hooks: any

dev_dependencies:
  lints: ^6.0.0
