name: complex_link_helper
description: Adds two json files to the built assets, and two more for linking.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  cli_config: ^0.2.0
  logging: ^1.3.0
  native_assets_cli: ^0.17.0-wip

dev_dependencies:
  lints: ^5.1.1
  path: ^1.9.0
  test: ^1.25.15
