name: package_with_assets
description: An example of using a package with assets.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  data_assets: ^0.19.0
  hooks: ^0.19.1
  logging: ^1.3.0
  meta: ^1.16.0
  record_use: ^0.3.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
