name: library_uris
description: >-
  Checks that library uris are as expected inside the link hook.

  For the VM, run `dart build cli` to trigger the link hook.

  For dart2js, `dart compile js --write-resources` and inspect the contents of
  the file.

version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  hooks: any
  library_uris_helper:
    path: ../library_uris_helper
  logging: ^1.3.0
  meta: ^1.18.0
  record_use: any

dev_dependencies:
  lints: ^6.0.0
