name: hooks_runner
description: >-
  This package is the backend that invokes build hooks.

version: 1.1.0-wip

repository: https://github.com/dart-lang/native/tree/main/pkgs/hooks_runner

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  code_assets: ^1.0.0 # Needed for OS for Target for KernelAssets.
  collection: ^1.19.1
  crypto: ^3.0.6
  file: ^7.0.1
  graphs: ^2.3.2
  hooks: ^1.0.0
  logging: ^1.3.0
  meta: ^1.16.0
  package_config: ^2.1.0
  pub_semver: ^2.2.0
  record_use: ^0.5.0-wip
  yaml: ^3.1.3

dev_dependencies:
  args: any
  custom_lint: ^0.8.1
  dart_flutter_team_lints: ^3.5.2
  data_assets: any # Used in tests.
  file_testing: ^3.0.2
  native_test_helpers:
    path: ../native_test_helpers/
  pub_formats: # Used in tests.
    path: ../pub_formats/
  repo_lint_rules:
    path: ../repo_lint_rules/
  test: ^1.25.15
