name: dart_app

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  native_add:
    path: ../native_add
  native_subtract:
    path: ../native_subtract

executables:
  dart_app:
