name: ffi
version: 2.1.2
description: Utilities for working with Foreign Function Interface (FFI) code.
repository: https://github.com/dart-lang/native/tree/main/pkgs/ffi

topics:
  - interop
  - ffi
  - codegen

environment:
  sdk: '>=3.3.0-279.1.beta <4.0.0'

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  test: ^1.21.2
