name: ffi
version: 2.1.3
description: Utilities for working with Foreign Function Interface (FFI) code.
repository: https://github.com/dart-lang/native/tree/main/pkgs/ffi
issue_tracker: https://github.com/dart-lang/native/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Affi

topics:
  - interop
  - ffi
  - codegen

environment:
  sdk: ^3.6.0

resolution: workspace
dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  test: ^1.21.2
