name: native_add_duplicate
description: Introduces the same dylib as native_add, to introduce a conflict.
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  logging: ^1.1.1
  native_add:
    path: ../native_add/
  native_assets_cli: ^0.8.0
  # native_assets_cli:
  #   path: ../../../native_assets_cli/
  native_toolchain_c: ^0.5.4
  # native_toolchain_c:
  #   path: ../../../native_toolchain_c/

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^3.0.0
  some_dev_dep:
    path: ../some_dev_dep/
  test: ^1.23.1
