name: add
description: A simple end-to-end example showcasing FFIgen.
publish_to: none

resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  code_assets: any
  ffi: ^2.1.4
  hooks: any
  native_toolchain_c: any

dev_dependencies:
  ffigen:
    path: '../../'
  test: ^1.25.15
