name: no_asset_for_link
description: A link hook, but no assets for link.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  code_assets: any
  data_assets: any
  hooks: any
  logging: ^1.3.0
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
