name: depend_on_fail_build
description: Has a dependency that fails to build.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  fail_build:
    path: ../fail_build/
  native_assets_cli: ^0.15.0-0

dev_dependencies:
  ffigen: ^18.0.0
  lints: ^5.1.1
  test: ^1.25.15
