name: native_add_version_skew_2
description: This package should no longer work due to being too old.
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  logging: ^1.3.0
  native_assets_cli: ^0.6.0
  native_toolchain_c: ^0.5.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  ffigen: ^18.0.0
  lints: ^6.0.0
  some_dev_dep:
    path: ../some_dev_dep/
  test: ^1.25.15
