name: add_asset_link
description: Add a dylib in the link step.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.1.1
  meta: ^1.12.0
  # native_assets_cli: ^0.9.0
  native_assets_cli:
    path: ../../../native_assets_cli/
  # native_toolchain_c: ^0.5.4
  native_toolchain_c:
    path: ../../../native_toolchain_c/

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
