name: code_assets
description: >-
  This library contains the hook protocol specification for bundling native code
  with Dart packages.

version: 1.0.0

repository: https://github.com/dart-lang/native/tree/main/pkgs/code_assets

topics:
  - assets
  - ffi
  - hooks
  - interop
  - native-assets

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  hooks: ^1.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  json_schema: ^5.2.0 # May only be used in tool/ and test/json_schema/.
  native_test_helpers:
    path: ../native_test_helpers/
  test: ^1.25.15
