name: code_assets
description: >-
  This library contains the hook protocol specification for bundling native code
  with Dart packages.

version: 0.19.4

repository: https://github.com/dart-lang/native/tree/main/pkgs/code_assets

topics:
  - assets
  - ffi
  - hooks
  - interop
  - native-assets

resolution: workspace

environment:
  sdk: '>=3.9.0-21.0.dev <4.0.0'

dependencies:
  collection: ^1.19.1
  hooks: ^0.19.5

dev_dependencies:
  custom_lint: ^0.7.5
  dart_flutter_team_lints: ^3.5.1
  json_schema: ^5.2.0 # May only be used in tool/ and test/json_schema/.
  repo_lint_rules:
    path: ../repo_lint_rules/
  test: ^1.25.15
  test_helpers:
    path: ../test_helpers/
