name: fail_on_os_sdk_version_link
description: Fails the build due to OS API levels.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  data_assets: any
  fail_on_os_sdk_version_linker:
    path: ../fail_on_os_sdk_version_linker/
  hooks: any

dev_dependencies:
  ffigen: ^20.0.0-dev.1
  lints: ^6.0.0
  test: ^1.25.15
