name: drop_dylib_recording
description: Generate two dylibs, remove one in linking based on recorded usage.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  logging: ^1.1.1
  meta: any
  hooks: any
  code_assets: any
  native_toolchain_c: any
  record_use: any

dev_dependencies:
  lints: any
  test: any
