name: dev_dependency_with_hook
description: Has a dev dependency with hook
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies: {}

dev_dependencies:
  ffigen: ^21.0.0-wip
  lints: ^6.0.0
  native_add:
    path: ../native_add/
  test: ^1.25.15
