name: native_add
description: Sums two numbers with native code.
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cli_config: ^0.1.1
  logging: ^1.1.1
  native_assets_cli:
    path: ../../../native_assets_cli/
  # native_toolchain_c: ^0.3.4+1
  native_toolchain_c:
    path: ../../../native_toolchain_c/

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^3.0.0
  some_dev_dep:
    path: ../some_dev_dep/
  test: ^1.23.1
