name: data_assets
description: >-
  This library contains the hook protocol specification for bundling data assets
  with Dart packages.

version: 0.19.3-wip

repository: https://github.com/dart-lang/native/tree/main/pkgs/data_assets

topics:
  - assets
  - hooks

resolution: workspace

environment:
  sdk: '>=3.9.0-21.0.dev <4.0.0'

dependencies:
  hooks: ^0.20.1-wip

dev_dependencies:
  custom_lint: ^0.7.5
  dart_flutter_team_lints: ^3.5.2
  json_schema: ^5.2.0 # May only be used in tool/ and test/json_schema/.
  native_test_helpers:
    path: ../native_test_helpers
  repo_lint_rules:
    path: ../repo_lint_rules/
  test: ^1.25.15
