name: data_assets
description: >-
  This library contains the hook protocol specification for bundling data assets
  with Dart packages.

version: 0.19.6

repository: https://github.com/dart-lang/native/tree/main/pkgs/data_assets

topics:
  - assets
  - hooks

resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  hooks: ^1.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  json_schema: ^5.2.0 # May only be used in tool/ and test/json_schema/.
  native_test_helpers:
    path: ../native_test_helpers
  test: ^1.25.15
