name: fail_build
description: Always fails to build
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  code_assets: ^0.19.2
  hooks: ^0.19.2

dev_dependencies:
  ffigen: ^18.0.0
  lints: ^5.1.1
  test: ^1.25.15
