name: simple_data_asset
description: Add and retrieve a data asset.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  data_assets: any
  hooks: any
  logging: ^1.3.0

dev_dependencies:
  test: ^1.25.15
