name: native_add_version_skew
description: Sums two numbers with native code.
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  logging: ^1.3.0
  native_assets_cli: ^0.15.0
  native_toolchain_c: ^0.12.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.1
  ffigen: ^20.0.0-dev.1
  lints: ^6.0.0
  some_dev_dep:
    path: ../some_dev_dep/
  test: ^1.25.15
