# Copyright (c) 2024, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

name: swiftgen
description: 'A tool for generating bindings that allow interop between Dart and Swift code.'
version: 0.0.1-wip
repository: https://github.com/dart-lang/native/tree/main/pkgs/swiftgen
issue_tracker: https://github.com/dart-lang/native/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aswiftgen

topics:
  - interop
  - ffi
  - swift
  - codegen

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  objective_c: ^1.1.0
  swift2objc: ^0.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  test: ^1.21.1

dependency_overrides:
  ffigen:
    path: ../ffigen/
  objective_c:
    path: ../objective_c/
  swift2objc:
    path: ../swift2objc/

executables:
  swiftgen:
