name: complex_link_helper
description: Adds two json files to the built assets, and two more for linking.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  data_assets: any
  hooks: any
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  path: ^1.9.0
  test: ^1.25.15
