name: reuse_dynamic_library
description: Dynamically link native libraries to each other.
version: 0.1.0
repository: https://github.com/dart-lang/native/tree/main/pkgs/hooks/example/build/native_dynamic_linking

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  code_assets: any
  hooks: any
  logging: ^1.3.0
  native_toolchain_c: any
  reusable_dynamic_library:
    path: ../reusable_dynamic_library/

dev_dependencies:
  ffigen: ^19.1.0
  lints: ^6.0.0
  test: ^1.21.0
