name: treeshaking_native_libs
description: Treeshake symbols by name from a native library.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  code_assets: any
  hooks: any
  logging: ^1.3.0
  native_toolchain_c: any

dev_dependencies:
  ffigen: ^18.0.0
  some_dev_dep:
    path: ../some_dev_dep/
  test: ^1.25.15
