name: record_use
description: >
  The serialization logic and API for the usage recording SDK feature.
repository: https://github.com/mosuem/record_use
version: 0.1.0-wip
environment:
  sdk: ^3.4.0

publish_to: none # hold off publishing while we are in experimental.

dependencies:
  collection: ^1.18.0
  protobuf: ^3.1.0
  pub_semver: ^2.1.4

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
  lints: ^4.0.0
  test: ^1.24.0
