name: record_use
description: >
  The serialization logic and API for the usage recording SDK feature.
version: 0.5.0-wip
repository: https://github.com/dart-lang/native/tree/main/pkgs/record_use

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  collection: ^1.19.1
  meta: ^1.17.0
  pub_semver: ^2.2.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  json_schema: ^5.2.2
  json_syntax_generator: ^0.1.0-wip
  native_test_helpers: ^0.1.0-wip
  test: ^1.25.15
