name: native_doc_dartifier
description: A library that converts code snippets from other languages into Dart
version: 0.0.1-pre
repository: https://github.com/dart-lang/native/tree/main/pkgs/native_doc_dartifier
issue_tracker: https://github.com/dart-lang/native/issues?q=is%3Aopen+label%3Apackage%3Anative_doc_dartifier

environment:
  sdk: ">=3.7.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  analyzer: ^7.4.5
  google_generative_ai: ^0.4.7
  jni: ^0.14.2

dev_dependencies:
  dart_flutter_team_lints: ^3.5.1
  jnigen: ^0.14.2
  test: ^1.26.0
