name: fail_on_os_sdk_version_linker
description: Fails the link due to OS API levels.
version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  code_assets: any
  hooks: any

dev_dependencies:
  ffigen: ^20.0.0-dev.1
  lints: ^6.0.0
  test: ^1.25.15
