name: complex_link
description: Prints "Tada!", but packages some assets while tree-shaking others
version: 0.1.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cli_config: ^0.2.0
  logging: ^1.1.1
  native_assets_cli:
    path: ../../../native_assets_cli/
  complex_link_helper:
    path: ../complex_link_helper/

dev_dependencies:
  lints: ^3.0.0
  test: ^1.23.1
  path: ^1.9.0
