name: treeshaking_native_assets
description: A sample on how to treeshake symbols using a build/link combo.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.1.1
  # native_assets_cli: ^0.5.0
  meta: ^1.12.0
  native_assets_cli:
    path: ../../../native_assets_cli/
  # native_toolchain_c: ^0.4.0
  native_toolchain_c:
    path: ../../../native_toolchain_c/

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
