name: host_name
description: A cross-platform Dart package for retrieving the local machine's hostname on major desktop and mobile platforms.
version: 0.1.0
repository: https://github.com/dart-lang/native/tree/main/pkgs/code_assets/example/build/hostname

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  code_assets: any
  ffi: ^2.1.4
  hooks: any

dev_dependencies:
  ffigen: ^21.0.0-wip
  test: ^1.25.15
