name: library_uris_helper
description: helper for library_uris

version: 0.1.0

publish_to: none

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  hooks: any
  logging: ^1.3.0
  meta: ^1.18.0
  record_use: any

dev_dependencies:
  lints: ^6.0.0
