name: no_asset_for_link
description: A link hook, but no assets for link.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.1.1
  meta: ^1.12.0
  # native_assets_cli: ^0.7.0
  native_assets_cli:
    path: ../../../native_assets_cli/

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
