name: objective_c_examples

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [main]
    paths:
      - '.github/workflows/objective_c.yaml'
      - 'pkgs/ffigen/**'
      - 'pkgs/native_test_helpers/**'
      - 'pkgs/objective_c/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/objective_c.yaml'
      - 'pkgs/ffigen/**'
      - 'pkgs/native_test_helpers/**'
      - 'pkgs/objective_c/**'
  schedule:
    - cron: "0 0 * * 0"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  build-flutter-example:
    runs-on: 'macos-latest'
    defaults:
      run:
        working-directory: pkgs/objective_c/example/flutter_app
    strategy:
      fail-fast: false
      matrix:
        xcode_version: ["16.1", "26.1.1"]
        ios_version: ["18.1"]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e
        with:
          channel: stable
      - name: Select the XCode version
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
      - name: Install iOS SDK
        run: xcodebuild -downloadPlatform iOS -buildVersion ${{ matrix.ios_version }}
      - name: Install dependencies
        run: flutter pub get
      - name: Build the example app for macos
        run: flutter build macos
      - name: Build the example app for ios
        run: flutter build ios --no-codesign
      - name: Check for xcode for analyzer warnings
        run: xcodebuild analyze -workspace macos/Runner.xcworkspace -scheme Runner -configuration Debug GCC_TREAT_WARNINGS_AS_ERRORS=YES

  build-command-line-example:
    runs-on: 'macos-latest'
    defaults:
      run:
        working-directory: pkgs/objective_c/example/command_line
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Run the example app
        run: dart run lib/main.dart
