name: objective_c

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [main, stable]
    paths:
      - '.github/workflows/objective_c.yaml'
      - 'pkgs/ffigen/**'
      - 'pkgs/native_test_helpers/**'
      - 'pkgs/objective_c/**'
  pull_request:
    branches: [main, stable]
    paths:
      - '.github/workflows/objective_c.yaml'
      - 'pkgs/ffigen/**'
      - 'pkgs/native_test_helpers/**'
      - 'pkgs/objective_c/**'
  schedule:
    - cron: "0 0 * * 0"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  # Check code formatting and static analysis.
  analyze:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: pkgs/objective_c/
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e
        with:
          channel: 'stable'
      - id: install
        name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'
      - name: Analyze code
        run: flutter analyze --fatal-infos
        if: always() && steps.install.outcome == 'success'

  test-mac:
    needs: analyze
    runs-on: 'macos-latest'
    defaults:
      run:
        working-directory: pkgs/objective_c/
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e
        with:
          channel: 'beta'
      - name: Install dependencies
        run: flutter pub get
      - name: Build test dylib
        # TODO(https://github.com/dart-lang/native/issues/1068): Remove this.
        run: dart --enable-asserts test/setup.dart
      - name: Install coverage
        run: dart pub global activate coverage
      - name: Run VM tests and collect coverage
        # TODO(https://github.com/dart-lang/sdk/issues/61791): Due to a compiler
        # crash, we have to run all tests individually. Once the fix lands in
        # Flutter beta, switch back to running tests with a single command.
        run: |
            dart test --coverage ./coverage test/autorelease_test.dart
            dart test --coverage ./coverage test/cf_string_test.dart
            dart test --coverage ./coverage test/converter_test.dart
            dart test --coverage ./coverage test/generate_code_test.dart
            dart test --coverage ./coverage test/interface_lists_test.dart
            dart test --coverage ./coverage test/ns_input_stream_test.dart
            dart test --coverage ./coverage test/ns_mutable_data_test.dart
            dart test --coverage ./coverage test/nsarray_test.dart
            dart test --coverage ./coverage test/nsdata_test.dart
            dart test --coverage ./coverage test/nsdate_test.dart
            dart test --coverage ./coverage test/nsdictionary_test.dart
            dart test --coverage ./coverage test/nsmutablearray_test.dart
            dart test --coverage ./coverage test/nsmutabledictionary_test.dart
            dart test --coverage ./coverage test/nsmutableset_test.dart
            dart test --coverage ./coverage test/nsnumber_test.dart
            dart test --coverage ./coverage test/nsset_test.dart
            dart test --coverage ./coverage test/nsstring_test.dart
            dart test --coverage ./coverage test/observer_test.dart
            dart test --coverage ./coverage test/os_version_test.dart
            dart test --coverage ./coverage test/selector_test.dart
            dart pub global run coverage:format_coverage --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage
      - name: Verify generated code is up to date
        # test/generate_code_test.dart runs the code generator, so if there are
        # any git-diffs at this point, it means the generated code is outdated.
        run: if [[ -n $(git status --porcelain | tee /dev/stderr) ]]; then echo -e "\nDIFF:"; git diff; false; fi
      - name: Upload coverage
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b
        with:
          flag-name: objective_c
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: pkgs/objective_c/coverage/lcov.info
      - name: Upload coverage
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b
        with:
          carryforward: "ffigen,jni,jnigen,native_pkgs_macos,native_pkgs_ubuntu,native_pkgs_windows,objective_c,swift2objc,swiftgen"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  build-example:
    needs: analyze
    runs-on: 'macos-latest'
    defaults:
      run:
        working-directory: pkgs/objective_c/example/
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build the example app
        run: flutter build macos
