name: hooks
description: >-
  A library that contains a Dart API for the JSON-based protocol for
  `hook/build.dart` and `hook/link.dart`.

version: 0.19.1

repository: https://github.com/dart-lang/native/tree/main/pkgs/hooks

topics:
  - assets
  - ffi
  - hooks
  - interop
  - native-assets

resolution: workspace

environment:
  sdk: '>=3.9.0-21.0.dev <4.0.0'

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  logging: ^1.3.0
  meta: ^1.16.0
  pub_semver: ^2.2.0
  yaml: ^3.1.3 # Used for reading pubspec.yaml to obtain the package name.

dev_dependencies:
  args: ^2.6.0
  code_assets: ^0.19.1 # Used for running tests with real asset types.
  custom_lint: ^0.7.5
  dart_flutter_team_lints: ^3.5.1
  data_assets: ^0.19.1 # Used for running tests with real asset types.
  file_testing: ^3.0.2
  glob: any
  json_schema: ^5.2.0 # May only be used in tool/ and test/json_schema/.
  json_syntax_generator:
    path: ../json_syntax_generator/
  path: ^1.9.1
  repo_lint_rules:
    path: ../repo_lint_rules/
  test: ^1.25.15
