publish_to: none

name: package_with_assets
description: An example of using a package with assets.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.1.1
  meta: ^1.12.0
  native_assets_cli: ^0.10.0
  # native_assets_cli:
  #   path: ../../../../native_assets_cli/
  record_use: ^0.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
