name: fail_on_os_sdk_version_link
description: Fails the build due to OS API levels.
version: 0.1.0

publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  fail_on_os_sdk_version_linker:
    path: ../fail_on_os_sdk_version_linker/
  # native_assets_cli: ^0.10.0
  native_assets_cli:
    path: ../../../native_assets_cli

dev_dependencies:
  ffigen:
    path: ../../../ffigen
  test: ^1.23.1
resolution: workspace
